before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rails test_app"
script:
  - "export DISPLAY=:99.0"
  - "bundle exec rspec spec"
rvm:
  - 2.1.2
  - 2.3.3
language: ruby
notifications:
  recipients:
    - JDutil@SpreeCommerce.com
